apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qrcode-api
  template:
    metadata:
      labels:
        app: qrcode-api
    spec:
      containers:
        - name: qrcode-api-container
          image: patelinbox/qrcodeapp:4.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: qrcode-api-service
spec:
  selector:
    app: qrcode-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer